spring:
  redis:
    host: 192.168.71.129
    port: 6379
    password: java@AnPLaPqcBGkrJ/Qxfp5GnsBu+bR3bbRm4e6s3KU39/C20fv2lG8dqnuUInf3XTqi
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  datasource:
    url: jdbc:mysql://192.168.71.129:3306/java?useUnicode=true&characterEncoding=utf8
    username: root
    password: eAjJfxS+2KTELRqsjm6hNNVOJ5bAe7y8LtpDkswvNof+r2h967SD5APzta0U7cyH22goZdEWMGQaMK4nMTh2Gg==
    driver-class-name: com.mysql.cj.jdbc.Driver
    #指定数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select current_timestamp;
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${config.decrypt.key}
      filter:
        config:
          #开启配置文件加密
          enabled: true

uploadPath: D:/cache/